name: Gerrit Stage

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Nexus Docker Login (Staging Registry)
        uses: lfreleng-actions/nexus-docker-login-action@v1
        with:
          nexus-docker-repo: "nexus3.onap.org:10003"
          nexus-username: ${{ secrets.LFIT_NEXUS_USERNAME }}
          nexus-password: ${{ secrets.LFIT_NEXUS_PASSWORD }}

      - name: Maven Stage and SBOM Generation
        uses: lfreleng-actions/maven-build-action@main
        with:
          jdk-version: "21"
          mvn-goals: "clean deploy"
          mvn-params: "-B -P docker -Dmaven.test.skip=true -Dcyclonedx.skip=false"
        env:
          MAVEN_USERNAME: ${{ secrets.LFIT_NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.LFIT_NEXUS_PASSWORD }}